### ISSUE TITLE
Tech Stack manager and search

### ISSUE THREAD

**Issue by TejasBaid** [al5ina5/discord-joie-bot#28]
One can add technologies to his/her profile which is searchable by anyone who is looking for people with the stack. It should work like the following :

`+add React` - `React has been added to your stack`

`+search React` - `The following developers work with React xxx xxx`

**Comment by al5ina5** [comment]
this is a great idea I love it! we will need to come up with a clever "parent command" like the way +country works

+tech +add react
+teach +search react
